### ISSUE TITLE
Feature Request - Base Path Override for nefarious and jackett

### ISSUE THREAD

**Issue by Ahuri3** [lardbit/nefarious#25] opened 2019-11-09 18:36 UTC
Hello !

Long story short : 

- I have bound the different ports to 127.0.0.1:XXX instead of :XXXX
- I have added an nginx to serve as reverse proxy and add https to the whole stack.
- I have added a base path override to jackett on /jackett

My nginx configuration is similar to this : 
```
location /jackett/ {
    proxy_pass         http://127.0.0.1:9117;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection keep-alive;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   X-Forwarded-Host $http_host;
}
```

It works fine for jackett itself but raised two issues : 

First of all : I haven't found a way to tell `nefarious` than the jackett base path has changed, this results in these kinds of errors : 

```
nefarious_1     | ERROR  2019-11-09 18:21:07,846  utils 18  140488504710976  HTTPConnectionPool(host='127.0.0.1', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc60119f7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
nefarious_1     | WARNING  2019-11-09 18:21:07,849  log 18  140488504710976  Bad Request: /api/settings/1/verify-jackett-indexers/
```
(Kinda obvious since the path has changed.)

Second : There is no option to changed the base path of nefarious itself, which complicates things if you planned to put it on `your.example.com/nefarious`

I wil try to take a look at both these issues !

**Comment by lardbit** [comment] 2019-11-10 01:46
Hey there.  Adding everything behind https is a great idea.  That's something I plan on incorporating into nefarious at some point.

You mentioned two issues but I only see the one relating to the proxied jackett URL?

As I understand, the issue is needing nefarious to query a different URL for jackett than the default host+port in the nefarious settings.  You'll see logic [here](https://github.com/lardbit/nefarious/blob/master/src/nefarious/jackett.py) that it would need updating.  

I suppose the only options would be to have this configurable in the main nefarious settings.  I'm just hesitant to add more advanced options that may confuse people.  Maybe an environment variable that can override that setting? I'm open to suggestions.

**Comment by Ahuri3** [comment] 2019-11-10 18:37
With this configuration :

```
location /nefarious {
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection keep-alive;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   X-Forwarded-Host $http_host;
    proxy_pass http://127.0.0.1:8000/;
}
``` 

Nginx doesn't seem able to serve as a reverse proxy with this configuration. Going to `my.website.com/nefarious` redirects me to : `my.website.com/static/index.html`

I'm not a nginx expert so it might be fixable with only nginx configuration. In that case the need for the different base path for jackett might also disappear.

**Comment by Ahuri3** [comment] 2019-11-10 20:20
I think I'm making progress : 

#### I have the `Jackett Base Path` field in the interface : 


![image](https://user-images.githubusercontent.com/4500365/68549954-7fdd2f80-03fe-11ea-9317-af87186ef32a.png)

I can see in the logs that for some queries the path to the jackett api is updated accordingly but not for all of them.

#### Not updated : 
```
celery_1        | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results/torznab/api?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go&t=indexers&configured=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa87ba74da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
celery_1        | [2019-11-10 20:11:04,515: ERROR/ForkPoolWorker-3] Task nefarious.tasks.watch_tv_show_season_task[43fb17b9-dfe1-413d-a10a-3b6365470fa2] raised unexpected: ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results/torznab/api?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go&t=indexers&configured=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa87ba74da0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
```
I think I know why, I have modified the `docker-compose.yml` to build from the source : 
```
nefarious:
  labels:
  - com.centurylinklabs.watchtower.enable=true
  #image: lardbit/nefarious
  build: .
```

But I forgot to do it for the `celery` service, so it's not using my changes.

#### Path is updated but I still get an error
```
nefarious_1     | ERROR  2019-11-10 20:04:56,891  utils 19  140425340569408  HTTPConnectionPool(host='127.0.0.1', port=9117): Max retries exceeded with url: /jackett/api/v2.0/indexers/all/results?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb74c31a080>: Failed to establish a new connection: [Errno 111] Connection refused',))
nefarious_1     | WARNING  2019-11-10 20:04:56,893  log 19  140425340569408  Bad Request: /api/settings/1/verify-jackett-indexers/
 ```

Even thought `curl http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go` works just fine

No idea what is going on there, will keep looking into it

**Comment by Ahuri3** [comment] 2019-11-10 21:02
I rebuilt the `celery` image and now it also has the updated paths !

```
celery_1        | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9117): Max retries exceeded with url: /jackett/api/v2.0/indexers/all/results/torznab/api?apikey=t8j6lnz1zlcmfj90u8yx40d513ug10go&t=indexers&configured=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8d7a706a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Now I have to figure out why it is not working !

**Comment by lardbit** [comment] 2019-11-10 21:40
Good working sorting it all out! What does your docker-compose file look like?

Yes, nefarious & celery are the only services contacting others via tcp.

**Comment by Ahuri3** [comment] 2019-11-10 21:49
Here is my docker-compose file :

```
version: '2.4'

services:

  # main application
  nefarious:
    labels:
    - com.centurylinklabs.watchtower.enable=true
    #image: lardbit/nefarious
    build: . # to build the local
    restart: always
    ports:
    - "127.0.0.1:8000:80"
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
    volumes:
    # persistent named volume for sqlite database
    - nefarious-db:/nefarious-db
    network_mode: host
    logging:
      options:
        max-size: 10m
    depends_on:
    - redis
    - jackett
    - celery

  # background task queue
  celery:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    #image: lardbit/nefarious
    build: .
    restart: always
    entrypoint: /env/bin/celery -A nefarious worker --beat --loglevel=INFO
    environment:
      # https://github.com/kennethreitz/dj-database-url
      DATABASE_URL: "sqlite:////nefarious-db/db.sqlite3"
      REDIS_HOST: "redis"
    volumes:
    # persistent named volume for sqlite database
    - nefarious-db:/nefarious-db
    logging:
      options:
        max-size: 10m
    depends_on:
      - redis

  # in-memory database for task queue
  redis:
    image: redis
    restart: always
    # TODO - use "expose" vs "ports" to limit external access
    ports:
    - "127.0.0.1:6379:6379"

  # torrent indexer service
  jackett:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: linuxserver/jackett
    mem_limit: 200m
    restart: always
    ports:
      - "127.0.0.1:9117:9117"
    logging:
      options:
        max-size: 10m
    volumes:
      - jackett-config:/config

  transmission:
    image: linuxserver/transmission
    volumes:
      # NOTE: the settings in this included file allow any IP to connect
      - type: bind
        source: ./transmission-settings.json
        target: /config/settings.json
        read_only: true
      # NOTE: update this path to point to where you want things downloaded to
      - /srv/docker/download:/downloads
    ports:
      - "127.0.0.1:9091:9091"

  cloudcmd:
    image: coderaiser/cloudcmd
    ports:
      - "127.0.0.1:18080:18080"
    volumes:
      - type: bind
        source: ./cloudcmd.json
        target: /root/.cloudcmd.json
        read_only: true
      - /srv/docker/download:/mnt/fs

  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/docker/nginx-config:/etc/nginx/conf.d
      - /srv/docker/certbot/conf:/etc/letsencrypt
      - /srv/docker/certbot/www:/var/www/certbot
      - /srv/docker/link:/var/www/link
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    network_mode: host
  certbot:
    image: certbot/certbot
    volumes:
      - /srv/docker/certbot/conf:/etc/letsencrypt
      - /srv/docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # auto update service
  # https://github.com/v2tec/watchtower
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: --label-enable --cleanup
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  nefarious-db:
    driver: local
  jackett-config:
    driver: local
```

I haven't used docker in a while so it might need to reread the networking documentation in order to make it work the way I wanted to (everything on 127.0.0.1 except nginx in front of them all, but keeping the containers's ability to talk to each other)

**Comment by lardbit** [comment] 2019-11-10 22:05
Oh I see what you're accomplishing now.  I think you should use the `expose` vs `ports` keyword in the `docker-compose.yml` file for everything sitting behind `nginx`.  That way, only internal containers can access those services, where `nginx` would be the only thing accessible from outside docker.

Double check the documentation but I think that's correct.  And you wouldn't need to specify `127.0.0.1` explicitly anywhere.

Let me know how it goes.

**Comment by lardbit** [comment] 2019-11-10 22:16
Yes I think using *expose* for internal containers should do the trick:

https://docs.docker.com/compose/compose-file/#expose

**Comment by Ahuri3** [comment] 2019-11-12 20:47
Expose seems to work very well !

**Comment by lardbit** [comment] 2019-11-12 20:52
Great! If you think your changes would benefit others in this setup, feel free to send along a Pull Request.

**Comment by lardbit** [comment] 2019-11-14 12:38
Closing this as it sounds like you found a way to accomplish this.

**Closed by lardbit** 2019-11-14 12:38 UTC
